### ISSUE TITLE
Bower repo and this github repo not in sync?

### ISSUE THREAD

**Issue by edfungus** [hunsalz/web-socket#1]
The bower component from `github.com/hunsalz/web-socket` seems to have been updated and doesn't match the code in here? The readme doesn't match the new code and that made it pretty confusing.  

Are you going to update this repo or is the bower version not correct?

**Comment by hunsalz** [comment]
@edfungus Sorry, for my delay. I overlooked your enquiry. - I did some clean-up work recently. Now, everything should be up to date again. Otherwise give me further hints, what you're missing.
